# Generated by Django 4.2.8 on 2024-01-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTraining', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create_At',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_Delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_Name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update_At',
            new_name='update_at',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
